### PR TITLE
Adjust markup and styles so that the Quick, Relative, and Absolute layouts all occupy the same bounds

### PR DESCRIPTION
**Pull request by cjcenizal**
Massaging the layout a bit so the size of the timepicker doesn't jump around as you switch between modes.

time_picker_panel_size

image

image

image

### CODE REVIEW

**Comment by cjcenizal** [comment]
@nreese Thoughts?

**Comment by nreese** [comment]
@cjcenizal I like the changes. The title and interface does not jump around as much. Only problem I see is that for smaller screen sizes, items float off screen to the left

**Comment by cjcenizal** [comment]
@nreese Good catch! I just fixed this. Can you take another look?

image

image

image

**Comment by nreese** [comment]
@cjcenizal Looks great

For the relative panel - why do the number input and select inputs need to be so long? Could those be shrunk so they fit side-by-side instead of stacked vertically?

**Comment by nreese** [comment]
One more suggestion, Since the `go` buttons are now on there own row, maybe they can be made a lot longer and centered or mored to the right. What do you think?

**Comment by cjcenizal** [comment]
Great ideas!

image

image

**Pull request merged**
